x = [0.1, 0.2, 0.3]

y = ?

y = W2(Sigmoid(W1(x)))

涉及到的矩阵都是全1矩阵（w是全1矩阵）

映射关系: x -> h -> y (3个x，4个h，2个y)

In [11]:
import numpy as np

def sigmoid(x): 
    return 1/(1 + np.exp(-x))

x = np.array([0.1, 0.2, 0.3])
print(x)

w1 = np.ones([3,4])
#print(w1)
w2 = np.ones([4,2])

y = ( sigmoid(x @ w1) )@ w2
print (y)





[0.1 0.2 0.3]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[2.58262522 2.58262522]
